name: doctor_one
description: "Dr.1 is a healthcare app designed to make medical care more accessible and convenient through an online platform. Imagine being able to care for your sick parents or loved ones from afar, without the constant worry of leaving them alone—Dr.1 provides the perfect solution. Our services include Hospital Assistant, Care at Home, Lab, Medicine Delivery, and Physiotherapy at Home, ensuring comprehensive healthcare support tailored to individual needs.
Whether you need a hospital assistant to accompany patients during visits, in-home care for daily support and companionship, or doorstep lab testing, Dr.1 has you covered. Our medicine delivery service ensures quick access to prescribed medications within two hours, while our physiotherapy service connects you with top professionals for in-home sessions or video consultations. With Dr.1, quality healthcare is just a tap away, bringing comfort and care to those who need it most.
"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.7
  open_file: ^3.5.10
  http: ^1.3.0
  path: ^1.8.0
  fluttertoast: ^8.2.10
  shared_preferences: ^2.4.0
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.0+3
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  another_flushbar: ^1.12.30
  firebase_messaging: ^15.2.1
  firebase_core: ^3.10.1
  firebase_analytics: ^11.4.1
  flutter_local_notifications: ^18.0.1
  curved_navigation_bar: ^1.0.6
  animated_bottom_navigation_bar: ^1.3.3
  lottie: ^3.2.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  dotted_border: ^2.1.0
  flutter_typeahead: ^4.0.0
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.10.0
  google_places_flutter: ^2.0.9
  flutter_dash: ^1.0.0
  in_app_update: ^4.2.3
  upgrader: ^11.3.1
  timeline_tile: ^2.0.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/firsticon.png
    - assets/images/anothre.png
    - assets/images/patient.png
    - assets/images/wheelchair.png
    - assets/images/successimage.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/d1/flask.png
    - assets/images/d1/medical-report.png
    - assets/images/d1/x-ray.png
    - assets/images/d1/nolog.jpg
    - assets/icons/account-circle-2-line.png
    - assets/icons/account-circle-2-fill.png
    - assets/icons/flask-line.png
    - assets/icons/flask-fill.png
    - assets/icons/home-9-line.png
    - assets/icons/home-9-fill.png
    - assets/icons/store-2-line.png
    - assets/icons/store-2-fill.png
    - assets/images/default_avatar.png
    - assets/images/medic.png
#  -----------------------------------medone
    - assets/medone/icons/medoneicon.png
    - assets/medone/icons/addmednotselected.png
    - assets/medone/icons/addmed.png
    - assets/medone/icons/homeicon.png
    - assets/medone/icons/homeiconnotselected.png
    - assets/medone/images/medicine.png
    - assets/medone/images/syrup.png
    - assets/medone/images/syringe.png
    - assets/medone/images/awaken.png
    - assets/medone/images/sleep.png
    - assets/medone/images/breakfast 1.png
    - assets/medone/images/medicine.png
    - assets/medone/images/clock.png
    - assets/medone/images/doctor.png
    - assets/medone/images/exercising.png
    - assets/medone/images/gallery.png
    - assets/medone/images/lunch-box.png
    - assets/medone/images/man.png
    - assets/medone/images/medicineone.png
    - assets/medone/images/ointment.png
    - assets/medone/images/roti 1.png
    - assets/medone/images/s.png
    - assets/medone/images/woman.png
    - assets/medone/icons/calendar-day.png
    - assets/medone/icons/info (2).png
    - assets/medone/lottie/profiledone.json
    - assets/medone/lottie/profiledone1.json
    - assets/medone/icons/multiSelect.png
#    ---------------------------
    - assets/droneicons/booklabtest.png
    - assets/droneicons/popularhealthcheck.png
    - assets/droneicons/xrays&mri.png
    - assets/droneicons/cancer.png
    - assets/droneicons/location.png
    - assets/droneicons/diabetes.png
    - assets/droneicons/fever.png
    - assets/droneicons/kidney.png
    - assets/droneicons/liver.png
    - assets/droneicons/popularhealthcheck.png
    - assets/droneicons/sex-education.png

  fonts:
    - family: AeonikTRIAL
      fonts:
        - asset: assets/fonts/AeonikTRIAL-Bold.otf
        - asset: assets/fonts/AeonikTRIAL-BoldItalic.otf
        - asset: assets/fonts/AeonikTRIAL-Light.otf
        - asset: assets/fonts/AeonikTRIAL-LightItalic.otf
        - asset: assets/fonts/AeonikTRIAL-Regular.otf
        - asset: assets/fonts/AeonikTRIAL-RegularItalic.otf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
